version: "3.9"

services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/pkg/mod
    env_file:
      - .env
    command: ["fresh"]
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
